# Generated by Django 2.2.16 on 2022-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220617_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title'),
        ),
    ]
